const Images = {
    blog_hero : require('./blog-hero.png'),
    about_hero : require('./about.jpg'),
    firstcard : require('./firstcard.png'),
    secondcard : require('./secondcard.png'),
    thirdcard : require('./thirdcard.png'),
    girlwithphone : require('./girlwithphone.png'),
    help_hero : require('./help-hero.jpg'),
    journey_hero : require('./journey-hero.png'),
    why_hero : require('./why-hero.png'),
    videosystem : require('./videosystem.png'),
    logo : require('./logo.svg'),
    appstore : require('./appstore.png'),
    playstore : require('./playstore.png'),
    mission : require('./mission.png'),
    vision: require('./vision.png'),
    about_hero2: require('./about2.png'),
    oracle: require('./oracle.png'),
    samsung: require('./samsung.png'),
    monday: require('./monday.png'),
    segment: require('./segment.png'),
    morpheus: require('./morpheus.png'),
    protonet: require('./protonet.png'),
    open: require('./open.png'),
    sponsor: require('./sponsor.png'),
    home: require('./home.png'),

}

export default Images